name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: lint
#        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
#    needs: [ lint ]
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: n8maninger/action-golang-test@503bdd1b410aa26740cad03f1214abc8beef5496
        with:
          args: "-race;-tags=testing debug netgo"