name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: n8maninger/action-golang-test@503bdd1b410aa26740cad03f1214abc8beef5496
        with:
          args: "-race"